In [24]:
import numpy as np 

In [25]:
one_dimensional = [1,2,3] # 1-d

In [26]:
np.array(one_dimensional)

array([1, 2, 3])

In [27]:
two_dimensional = [[4,5,6],[1,2,3]] # 2-d

In [28]:
np.array(two_dimensional)

array([[4, 5, 6],
       [1, 2, 3]])

In [30]:
three_dimensional = [[[1,5,6],[2,5,6],[3,5,6]],[[4,5,6],[5,5,6],[6,5,6]]] # 3_d

In [32]:
np.array(three_dimensional)

array([[[1, 5, 6],
        [2, 5, 6],
        [3, 5, 6]],

       [[4, 5, 6],
        [5, 5, 6],
        [6, 5, 6]]])

In [34]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [40]:
np.zeros((2,4,3)) # 2 layers, 4 rows, 3 coloumns

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]]])

In [43]:
np.arange(0,10,2) 

array([0, 2, 4, 6, 8])

In [45]:
np.linspace(0,1,10)

array([ 0.        ,  0.11111111,  0.22222222,  0.33333333,  0.44444444,
        0.55555556,  0.66666667,  0.77777778,  0.88888889,  1.        ])

In [47]:
np.eye(5) #eye = identitity matrix :-D

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

#### Numpy Indexing and selection

In [48]:
arr = np.arange(0,11)

In [49]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [54]:
arr_copy = arr.copy() # to actually copy. Other times numpy will just refer to the actual value without copying them

In [58]:
arr_2d = np.arange(50).reshape(5,10)

In [59]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [62]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [64]:
arr_2d * 5 # scaling

array([[  0,   5,  10,  15,  20,  25,  30,  35,  40,  45],
       [ 50,  55,  60,  65,  70,  75,  80,  85,  90,  95],
       [100, 105, 110, 115, 120, 125, 130, 135, 140, 145],
       [150, 155, 160, 165, 170, 175, 180, 185, 190, 195],
       [200, 205, 210, 215, 220, 225, 230, 235, 240, 245]])